#pragma once

#define TAPPING_TERM 200

// #define COMBO_TERM 200

// #define PERMISSIVE_HOLD

#define IGNORE_MOD_TAP_INTERRUPT

#define TAPPING_FORCE_HOLD

// #define RETRO_TAPPING

#define COMBO_COUNT 10

// #define COMBO_ALLOW_ACTION_KEYS